version: '3.7'

services:
  pg:
    image: bitnami/postgresql:latest
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_USER: docker
      POSTGRES_DB: next-saas-db
 